baseURL: https://rohin-nayar.github.io/Finance-Blog/
languageCode: en-us
title: My New Hugo Site
module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod
theme: ["PaperMod"]
params:
  homeInfoParams:
    Title: "PaperMod's Demo"
    Content: >
      👋 Welcome to the Finance Blog!

  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/rohin-nayar"
    - name: LinkedIn
      title: Connect on LinkedIn
      url: "https://www.linkedin.com/in/rohinnayar/"
    - name: Leetcode
      title: View Leetcode Profile
      url: "https://leetcode.com/u/RohinN/"